nodeLinker: node-modules

checksumBehavior: update

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: 'https://github.com/mskelton/yarn-plugin-outdated/raw/main/bundles/@yarnpkg/plugin-outdated.js'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
  cpu:
    - 'current'
    - 'x86'
  libc:
    - 'current'
    - 'glibc'
